version: '3.8'
services:
  miapp:
    image: miapp-docker:1.0
    ports:
      - "8080:8080"
    environment:
      MENSAJE: "Hola desde docker-compose"
    command: ["dotnet", "run", "--urls", "http://0.0.0.0:8080"]